[platformio]
default_envs = prod_lilygo_t_beam_sx1262

[env:prod_lilygo_t_beam_sx1262]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
build_flags = 
    -std=gnu++17
build_unflags =
    -std=gnu++11
    -std=c++11
lib_deps =
    https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/archive/refs/tags/5.0.1.zip
    adafruit/Adafruit BMP085 Library@^1.2.4
    https://github.com/lewisxhe/XPowersLib.git